export const nickNames: { [key: string]: string[] } = {
  noVotes: [
    'The Invisible One',
    "The Ghost Voter's Choice",
    'The Lonely Leader',
    'The Zero Hero',
    'The Undiscovered Gem',
    "The Silent Majority's Favorite",
    'The Null-and-Void Nominee',
    "The Unopinionated's Option",
    'The Tabula Rasa Talent',
    'The Oblivious Option',
  ],
  '-80': [
    'Widely Despised',
    'Absolutely Loathed',
    'Universally Detested',
    'Incredibly Hated',
    'Monstrously Unpopular',
    'Notably Repugnant',
    'Notoriously Detestable',
    'Spectacularly Despicable',
    'Astoundingly Abhorrent',
    'Incredibly Disdained',
    'Exceptionally Execrable',
    'Profoundly Despised',
    'Outrageously Offensive',
    'Immensely Irritating',
    'Terribly Troublesome',
  ],
  '-60': [
    'Very Disliked',
    'Generally Unfavored',
    'Unpopular',
    'Largely Shunned',
    'Often Overlooked',
    'Rarely Revered',
    'Infrequently Favored',
    'Scarcely Celebrated',
    'Seldom Treasured',
    'Infrequently Idolized',
    'Not Usually Valued',
    'Underwhelmingly Underappreciated',
    'Barely Admired',
    'Seldom Exalted',
    'Hardly Honored',
  ],
  '-40': [
    'Not So Popular',
    'Mildly Disliked',
    'Seldom Preferred',
    'Rarely Adored',
    'Somewhat Unpopular',
    'Less Than Loved',
    'Infrequently Invited',
    'Barely Befriended',
    'Sporadically Supported',
    'Occasionally Overlooked',
    'Rarely Revered',
    'Hardly Heralded',
    'Seldom Saluted',
    'Not Often Noted',
    'Underappreciated',
  ],
  '-20': [
    'Slightly Unliked',
    'Occasionally Disregarded',
    'Infrequently Preferred',
    'Not Too Popular',
    'Mildly Unpopular',
    'Sporadically Spurned',
    'Lightly Disregarded',
    'Marginally Overlooked',
    'Barely Belittled',
    'Seldom Snubbed',
    'Not Frequently Favored',
    'Rarely Recognized',
    'Occasionally Ignored',
    'Infrequently Insulted',
    'Sometimes Scorned',
  ],
  '0': [
    'Neutral',
    'Ambivalent Popularity',
    'Neither Loved nor Hated',
    'Indifferent Reception',
    'Middle of the Pack',
    'Pleasantly Average',
    'Moderately Middling',
    'Perfectly Median',
    'Agreeably Ambiguous',
    'Safely Standard',
    'Comfortably Common',
    'Regularly Regular',
    'Ordinarily Ordinary',
    'Typically Typical',
    'Conventionally Conventional',
  ],
  '20': [
    'Slightly Liked',
    'Somewhat Popular',
    'Occasionally Adored',
    'Often Preferred',
    'Generally Appreciated',
    'Infrequently Applauded',
    'Rarely Revered',
    'Seldom Celebrated',
    'Not Often Noted',
    'Sometimes Supported',
    'Regularly Recognized',
    'Commonly Complimented',
    'Often Okayed',
    'Sometimes Smiled At',
    'Marginally Mentioned',
  ],
  '40': [
    'Quite Liked',
    'Pretty Popular',
    'Frequently Adored',
    'Popular',
    'Liked by Many',
    'Admirably Accepted',
    'Regularly Revered',
    'Commonly Celebrated',
    'Often Applauded',
    'Notably Noted',
    'Seldom Snubbed',
    'Rarely Repudiated',
    'Ordinarily Overjoyed',
    'Frequently Favored',
    'Largely Liked',
  ],
  '60': [
    'Very Popular',
    'Widely Preferred',
    'Unusually Adored',
    'Loved by Many',
    'Highly Liked',
    'Commonly Celebrated',
    'Notably Noteworthy',
    'Quite the Darling',
    'Frequently Favored',
    'Seldom Scorned',
    'Rarely Rejected',
    'Admirably Accepted',
    'Incredibly Invited',
    'Pretty Popular',
    'Very Valued',
  ],
  '80': [
    'Most Loved',
    'Almost Universally Adored',
    'Monumentally Popular',
    'Extremely Loved',
    'Super Popular',
    'Astoundingly Admired',
    'Outrageously Adored',
    'Exceptionally Esteemed',
    'Incredibly Idolized',
    'Universally Uplifted',
    'Prolifically Praised',
    'Hugely Honored',
    'Significantly Sought-after',
    'Tremendously Treasured',
    'Astoundingly Applauded',
  ],
  '100': [
    'Most Loved',
    'Almost Universally Adored',
    'Monumentally Popular',
    'Extremely Loved',
    'Super Popular',
    'Loved Beyond Measure',
    'Adored Above All',
    'Universally Unbeatable',
    'Epicly Esteemed',
    'Powerfully Praised',
    'Idolized Immensely',
    'Honored Highly',
    'Treasured Above All',
    'Incredibly Irresistible',
    'Exceptionally Exalted',
  ],
}

export const descriptions: { [key: string]: string[] } = {
  noVotes: [
    "This personality is so untouched it's like a white canvas in a modern art museum. Everyone sees it, but no one knows what to do with it.",
    "Zero votes on this one! This personality's popularity contest feels like a ghost town.",
    'This personality has received as many votes as a sloth wins sprints.',
    "Looks like this personality's vote count matches the number of people who've been to the moon. Yup, it's that exclusive!",
    "No votes here, this personality's polling booth is as vacant as a gym in January.",
    "The vote count is at 'Big Foot' levels of sightings. Purely mythical!",
    'Votes for this personality are as elusive as a unicorn at the end of a double rainbow.',
    "This personality's votes are like pens at a bank, they seem to have all mysteriously disappeared.",
    'The voting for this personality is as dry as the humor in a British comedy. Not a chuckle in sight!',
    'No votes yet, this personality is as uncharted as the dark side of the moon.',
  ],
  '-80': [
    'As welcome as a skunk at a lawn party.',
    'Liked as much as a sandpaper massage.',
    'More avoided than a porcupine hug.',
    'Gets along like a cat at a dog show.',
    'About as popular as a root canal.',
    'Preferred as much as a glass of milk in a heatwave.',
    'Less loved than a Monday morning.',
    'Has a fan club smaller than a desert oasis.',
    'Their charm is equivalent to a wet blanket.',
    'Elicits less joy than a tax audit.',
  ],
  '-60': [
    'More ignored than elevator music.',
    'Less welcomed than a snowstorm in July.',
    'The human equivalent of a traffic jam.',
    'Liked less than unsolicited advice.',
    'More avoided than spoilers for a popular show.',
    'As appealing as a cold shower in winter.',
    'Less popular than a fork in a sugar bowl.',
    'Attracts affection like a picnic attracts ants.',
    'Their social standing is a slippery slope.',
    'Less admired than a flat tire.',
  ],
  '-40': [
    "Treated like a forgotten New Year's resolution.",
    'More overlooked than a typo in a novel.',
    'A social butterfly without wings.',
    'As liked as socks on Christmas.',
    'About as popular as an encore at a piano recital.',
    'Less desired than a diet on a holiday.',
    'A wallflower at the dance of life.',
    'As embraced as a change in the office coffee.',
    'About as welcome as a hiccup in a meditation session.',
    'Less popular than a rerun of a cancelled show.',
  ],
  '-20': [
    'Treated like the optional salad at a steakhouse.',
    'As overlooked as an empty toilet paper roll.',
    'Less memorable than the third hobbit from the left in a movie.',
    'Has the appeal of a lukewarm coffee.',
    'Popular as a salad in a candy store.',
    "The human equivalent of 'Terms and Conditions'.",
    'Could be more liked, like a sunny day in Seattle.',
    'Is to popularity what a tumbleweed is to a desert.',
    "Has a popularity ranking equivalent to a left shoe's right lace.",
    "As embraced as a 'close door' button in an elevator.",
  ],
  '0': [
    'The Switzerland of popularity.',
    'A wild card in the game of public opinion.',
    'Liked as much as they are disliked, perfectly balanced.',
    'As neutral as a beige sweater.',
    'A perfect score in the game of indifference.',
    'About as controversial as vanilla ice cream.',
    'Neither a shooting star nor a sinking stone in the sea of popularity.',
    "In the realm of public opinion, they're the 'maybe' in a yes/no question.",
    'Their popularity barometer is having a day off.',
    'As controversial as a potato in a vegetarian meal.',
  ],
  '20': [
    'Slightly more liked than a free pen.',
    'As popular as a sunny day in England.',
    'They are to popularity what a light breeze is to a windstorm.',
    'Liked a bit more than an extra hour of sleep.',
    'Treated like a clean public restroom.',
    'About as appealing as finding money in old pants.',
    'As welcome as a non-urgent email.',
    'About as popular as a comfy chair after a long day.',
    'Gets along like a cat in a fish market.',
    'Their popularity is growing, like a snowball down a hill.',
  ],
  '40': [
    'Liked more than a discounted item.',
    'As welcome as a pleasant surprise.',
    'As popular as a cool breeze on a hot day.',
    'Well-received like a lost item found.',
    'More popular than a high speed internet connection.',
    'Preferred as much as a backseat on a crowded bus.',
    'As welcome as a weekend after a busy week.',
    'Has the charm of a surprise gift.',
    'As appealing as a good joke at a party.',
    'Their charm works like a cozy blanket on a cold night.',
  ],
  '60': [
    'Popular as a cozy fireplace in winter.',
    'Liked as much as a good joke.',
    'More popular than a summer vacation.',
    'As welcome as a day off.',
    'Treated like a VIP ticket to a sold-out concert.',
    'About as beloved as a puppy in a room full of dog lovers.',
    'Their popularity rating is higher than a kite on a windy day.',
    'As desired as a good book on a rainy day.',
    'Elicits more joy than a perfect coffee on a lazy morning.',
    'About as appreciated as a heartfelt compliment.',
  ],
  '80': [
    'Adored as much as a pleasant surprise on a bad day.',
    'Their popularity is spreading faster than a cute cat video on the internet.',
    'As popular as a tax refund.',
    'As loved as a free upgrade.',
    'As appealing as a shooting star on a clear night.',
    'Their social score is hotter than a trending hashtag.',
    'As cherished as an old family photo.',
    'More popular than the snooze button on a Monday morning.',
    'As loved as a goodnight kiss.',
    "Their charm is as contagious as a baby's laughter.",
  ],
  '100': [
    'As popular as a superhero in a world of villains.',
    'The human equivalent of a four-leaf clover.',
    'As loved as the first cup of coffee in the morning.',
    'More cherished than a handwritten letter.',
    'As appreciated as a comforting hug.',
    'About as adored as a favorite childhood memory.',
    'As popular as a melody in a catchy song.',
    'As loved as a beautiful sunset after a long day.',
    'Their popularity is as contagious as a yawn.',
    'Adored as much as a free gourmet meal.',
  ],
}
