export const nickNames: { [key: string]: string[] } = {
  '-80': [
    'Widely Despised',
    'Absolutely Loathed',
    'Universally Detested',
    'Incredibly Hated',
    'Monstrously Unpopular',
    'Notably Repugnant',
    'Notoriously Detestable',
    'Spectacularly Despicable',
    'Astoundingly Abhorrent',
    'Incredibly Disdained',
    'Exceptionally Execrable',
    'Profoundly Despised',
    'Outrageously Offensive',
    'Immensely Irritating',
    'Terribly Troublesome',
  ],
  '-60': [
    'Very Disliked',
    'Generally Unfavored',
    'Unpopular',
    'Largely Shunned',
    'Often Overlooked',
    'Rarely Revered',
    'Infrequently Favored',
    'Scarcely Celebrated',
    'Seldom Treasured',
    'Infrequently Idolized',
    'Not Usually Valued',
    'Underwhelmingly Underappreciated',
    'Barely Admired',
    'Seldom Exalted',
    'Hardly Honored',
  ],
  '-40': [
    'Not So Popular',
    'Mildly Disliked',
    'Seldom Preferred',
    'Rarely Adored',
    'Somewhat Unpopular',
    'Less Than Loved',
    'Infrequently Invited',
    'Barely Befriended',
    'Sporadically Supported',
    'Occasionally Overlooked',
    'Rarely Revered',
    'Hardly Heralded',
    'Seldom Saluted',
    'Not Often Noted',
    'Underappreciated',
  ],
  '-20': [
    'Slightly Unliked',
    'Occasionally Disregarded',
    'Infrequently Preferred',
    'Not Too Popular',
    'Mildly Unpopular',
    'Sporadically Spurned',
    'Lightly Disregarded',
    'Marginally Overlooked',
    'Barely Belittled',
    'Seldom Snubbed',
    'Not Frequently Favored',
    'Rarely Recognized',
    'Occasionally Ignored',
    'Infrequently Insulted',
    'Sometimes Scorned',
  ],
  '0': [
    'Neutral',
    'Ambivalent Popularity',
    'Neither Loved nor Hated',
    'Indifferent Reception',
    'Middle of the Pack',
    'Pleasantly Average',
    'Moderately Middling',
    'Perfectly Median',
    'Agreeably Ambiguous',
    'Safely Standard',
    'Comfortably Common',
    'Regularly Regular',
    'Ordinarily Ordinary',
    'Typically Typical',
    'Conventionally Conventional',
  ],
  '20': [
    'Slightly Liked',
    'Somewhat Popular',
    'Occasionally Adored',
    'Often Preferred',
    'Generally Appreciated',
    'Infrequently Applauded',
    'Rarely Revered',
    'Seldom Celebrated',
    'Not Often Noted',
    'Sometimes Supported',
    'Regularly Recognized',
    'Commonly Complimented',
    'Often Okayed',
    'Sometimes Smiled At',
    'Marginally Mentioned',
  ],
  '40': [
    'Quite Liked',
    'Pretty Popular',
    'Frequently Adored',
    'Popular',
    'Liked by Many',
    'Admirably Accepted',
    'Regularly Revered',
    'Commonly Celebrated',
    'Often Applauded',
    'Notably Noted',
    'Seldom Snubbed',
    'Rarely Repudiated',
    'Ordinarily Overjoyed',
    'Frequently Favored',
    'Largely Liked',
  ],
  '60': [
    'Very Popular',
    'Widely Preferred',
    'Unusually Adored',
    'Loved by Many',
    'Highly Liked',
    'Commonly Celebrated',
    'Notably Noteworthy',
    'Quite the Darling',
    'Frequently Favored',
    'Seldom Scorned',
    'Rarely Rejected',
    'Admirably Accepted',
    'Incredibly Invited',
    'Pretty Popular',
    'Very Valued',
  ],
  '80': [
    'Most Loved',
    'Almost Universally Adored',
    'Monumentally Popular',
    'Extremely Loved',
    'Super Popular',
    'Astoundingly Admired',
    'Outrageously Adored',
    'Exceptionally Esteemed',
    'Incredibly Idolized',
    'Universally Uplifted',
    'Prolifically Praised',
    'Hugely Honored',
    'Significantly Sought-after',
    'Tremendously Treasured',
    'Astoundingly Applauded',
  ],
  '100': [
    'Most Loved',
    'Almost Universally Adored',
    'Monumentally Popular',
    'Extremely Loved',
    'Super Popular',
    'Loved Beyond Measure',
    'Adored Above All',
    'Universally Unbeatable',
    'Epicly Esteemed',
    'Powerfully Praised',
    'Idolized Immensely',
    'Honored Highly',
    'Treasured Above All',
    'Incredibly Irresistible',
    'Exceptionally Exalted',
  ],
}
